### PR TITLE
refactoring of track ingestion

### PR DESCRIPTION
**Pull request by luigiberducci**
Update track ingestion:
- env constructor takes only the map name (e.g., Skirk, Vegas), no need to specify map extension anymore.
- track information will be automatically loaded into a `Track` object.
- raceline and centerline will be loaded as `Raceline` object, if corresponding files exist in the map dir.
- `map` directory moved from `f110_gym/envs` to `f110_gym`.

I will open a separate issue for the integration and automatic download of `f1tenth_racetracks`.

### CODE REVIEW

**Comment by hzheng40** [comment]
I've added the ingestion of the track files and extraction to the correct directories.
Whenever the track classes are imported, the download check is triggered.
Checking whether the track files already exists is still a little hacky.
Someone else should test it out.
Otherwise, all looks good and works on my side with waypoint follow.

**Review by hzheng40 — APPROVED** [review]
LGTM

**Comment by luigiberducci** [comment]
Shall we pack each track individually so that we can check and eventually download a specific track?
It could be convenient if we don't want to download all of them, easy to check, and easy to extend to new tracks (even if it won't happen so frequently)

**Comment by hzheng40** [comment]
@luigiberducci That's true. I'll package the tracks separately and move the download into `find_track_dir` probably?

**Comment by hzheng40** [comment]
Updated, @luigiberducci. Should we also consider ignoring uppercase letters in the track name?

**Comment by luigiberducci** [comment]
Ok, looks good to me. 

I corrected minor things:
- fix warning unclosed tmp file, 
- add map to `.gitignore`,
- add a test

About uppercase, I don't have strong preferences. I have just kept the convention from `f1tenth_racetracks`.
However, we should decide if keeping the old tracks (without raceline and centerline) or get rid of them.

**Pull request merged**
