### PR TITLE
Updated renderer calls to reference self

### PR DESCRIPTION
**Pull request by nandantumu**
Fixed bugs where renderer would not dereference or close properly. Calls were previously made to the object type, not self. Now the renderer is contained within the env.

### CODE REVIEW

**Comment by hzheng40** [comment]
This was on purpose. Instead of instance attributes, everything is class attributes now in order to reduce size when pickled.

**Comment by nandantumu** [comment]
Updated to ensure renderer is not saved, tested this with Unittest

**Comment by stanleybak** [comment]
Not sure if this is still planning to be merged or not. There may be issues with deleting `self.renderer` in `__getstate__`, in that if I have testing code where I pickle and restore the renderer many times it would keep creating new renderers with this version, which could be slow and lead to problems. Was there an issue with having it just be a class variable?

**Comment by nandantumu** [comment]
I have reached a workaround for the issue I was having, where I was trying to have multiple envs open. That is no longer an issue, so I've closed the PR

**Pull request closed without merging**
