### PR TITLE
Feature/model selection

### PR DESCRIPTION
**Pull request by AhmadAmine998**
Addresses #70

### CODE REVIEW

**Review by luigiberducci — CHANGES_REQUESTED** [review]
Looks fine to me.

Before approval, it would be great if we can check the code in `dynamic_models.py` and unit-tests `dynamic_test.py`. I see there is duplicate code, the class `DynamicsTest` is defined in both files.

**Comment by luigiberducci** [comment]
- merge latest changes from `v1.0.0`
- update dynamics model creation to follow convention `from_string(dynamics: str`) as for `action` and `observation`
- move integrator and dynamics enum to `dynamic_models.py`
- delete obsolete test/code duplicates in `dynamic_models.py` and `dynamics_test.py`

@AhmadAmine998 please check

**Review by luigiberducci — APPROVED** [review]

**Comment by luigiberducci** [comment]
@hzheng40 @nandantumu please review

**Review by hzheng40 — APPROVED** [review]
LGTM

**Pull request merged**
